import type { Section } from "../types";

export const FARM: Section = {
  id: "farm",
  title: "Pals de base et ranch",
  subtitle:
    "Toute la prod passe par vos Pals. Grande nouveauté 1.0 : les niveaux de travail montent désormais jusqu'à **10** (contre 5 avant), via condensation et manuels de compétence. Les meilleurs **passifs de vitesse de travail** sont maintenant, dans l'ordre : **Main du démon** (Demon's Hand, le nouveau top), Remarquable savoir-faire, Artisan, Work Slave. Les passifs **nocturnes** (bossent la nuit) restent clés.",
  group: "Les Pals",
  icon: "wheat",
  accent: "amber",
  blocks: [
    { kind: "sub", title: "Étoiler un Pal : le Condenseur" },
    {
      kind: "p",
      text: "Pour monter un Pal en étoiles (jusqu'à 4), c'est le **Condenseur d'essence de Pal**, débloqué dans l'arbre de techno au **niveau 14**. Vous mettez votre Pal principal dedans et vous le nourrissez de **doublons de la même espèce** : il faut 4 copies pour la 1re étoile, puis de plus en plus ensuite. Chaque étoile monte les **stats** ET l'**aptitude de travail**. C'est pour ça qu'on capture 5 de chaque espèce et qu'on garde les doublons : un ouvrier étoilé bosse bien mieux, un cogneur étoilé tape plus fort.",
    },
    {
      kind: "cards",
      cols: 2,
      items: [
        {
          accent: "amber",
          title: "Bien s'y prendre",
          list: [
            "Choisissez le **bon Pal en premier** (celui qui reste), le doublon à sacrifier en second.",
            "Le doublon ne doit pas être **verrouillé / favori**, sinon ça bloque.",
            "Vous pouvez fusionner un Pal \"raté\" déjà étoilé dans un bon Pal en **1:1** : un doublon 4 étoiles donne 4 étoiles d'un coup. Pratique si vous avez maxé le mauvais.",
            "Nouveauté 1.0 : les **fruits étoilés** montent une étoile **instantanément**, sans farmer les doublons. Gros gain de temps.",
          ],
        },
        {
          accent: "amber",
          title: "Ne pas confondre avec la Statue du Pouvoir",
          body: "La grande statue d'Anubis, elle, utilise des **âmes de Pal** pour booster PV, attaque, défense et vitesse de travail (jusqu'à +18%). C'est un système **séparé** du starring, les deux se cumulent. Bon à savoir : cette statue permet aussi de **rembourser les âmes** contre un peu d'or si vous vous êtes trompé de Pal.",
        },
      ],
    },
    { kind: "sub", title: "Meilleurs ouvriers par compétence" },
    {
      kind: "table",
      head: ["Travail", "Meilleur Pal (accessible)", "Note"],
      rows: [
        ["Fabrication (handiwork)", "{{Anubis}} + {{Sekhmet}}", "Le duo cassé. Voir combo ci-dessous. Aussi Venusa, Wistella (6)."],
        ["Minage", "{{Blazamut}} (7)", "Le plus haut trouvé. Sinon Anubis (6), Menasting (5), Mammorest."],
        ["Allumage (kindling)", "{{Suzaku}} (5)", "Meilleur jusqu'au endgame, via reproduction. Sinon Jormuntide Ignis, Gangler Ignis (nocturne)."],
        ["Arrosage", "{{Gangler}} (5)", "Meilleur début jusqu'au endgame. Aussi Penking. Shell Long (8) au World Tree."],
        ["Plantation", "{{Carbonora}} (6)", "Meilleur pour planter et récolter. Aussi Lyleen (7), Verdash."],
        ["Récolte (gathering)", "{{Venusa}} (6)", "Six en récolte et en fabrication. Aussi Lyleen (6)."],
        ["Électricité", "{{Dynamov}} (6)", "Excellent. Sinon Grizzbolt (5), Orserk (8) plus tard."],
        ["Transport", "{{Wumpo}} (6)", "Booste aussi le transport des autres Pals."],
        ["Refroidissement", "{{Wumpo}} (5) / {{Penking}}", "Chillet marche aussi."],
        ["Bûcheronnage", "{{Celaray}} deer (7)", "Aussi Warsack (4), Mammorest."],
        ["Pharmacie (medicine)", "{{Wistella}} (6)", "Aussi Lyleen (5), Venusa (5), Vaelet."],
      ],
    },
    {
      kind: "callout",
      tone: "combo",
      label: "Le combo Anubis + Sekhmet",
      text: "Anubis est déjà excellent (fabrication et minage niveau 6). Capturez une **Sekhmet ALPHA condensée 4 fois** : sa compétence booste la vitesse de travail d'Anubis, et surtout, si Anubis et Sekhmet fabriquent au même établi, l'efficacité grimpe de +400%. La vitesse de travail de Sekhmet peut dépasser 800 (contre 180 à 200 pour un Anubis normal). Ça craft quasi instantanément.",
    },
    { kind: "sub", title: "Les Pals-aura : +1 à toute la base" },
    {
      kind: "p",
      text: "Ces Pals, juste en étant **sortis à la base**, donnent +1 dans une compétence à TOUS vos autres Pals qui l'ont (un 9 passe à 10, un 7 à 8). Ils restent à +1 même condensés 4 étoiles. Faciles à capturer, aucune stat requise, mets-en un de chaque type utile.",
    },
    {
      kind: "table",
      head: ["Compétence", "Pal-aura"],
      rows: [
        ["Minage", "{{Tecturus}}"],
        ["Fabrication", "{{Ribunny}}"],
        ["Pharmacie", "{{Mau Corolla}}"],
        ["Culture (ferme)", "{{Cinnamoth}}"],
        ["Plantation", "{{Petallia}}"],
        ["Récolte", "{{Clovie}}"],
        ["Arrosage", "{{Aemyo}}"],
        ["Allumage", "{{Katress Ignis}}"],
        ["Transport", "{{Woolipop}}"],
        ["Refroidissement", "{{Smokey Cryst}}"],
      ],
    },
    { kind: "sub", title: "Atteindre le niveau 10 sans manuels (endgame)" },
    {
      kind: "p",
      text: "Un Pal qui n'a **qu'une ou deux compétences de travail** concentre tous ses bonus de condensation dessus, et atteint donc le **niveau 10 rien qu'en le condensant 4 étoiles**, sans dépenser de manuels. Les meilleurs par tâche :",
    },
    {
      kind: "list",
      items: [
        "**Allumage** : {{Jormuntide Ignis}} (allumage seul), ou **Renjishi** qui atteint 10 en allumage ET fabrication (parfait pour la cuisine antique).",
        "**Fabrication** : {{Soulaine}} (le seul qui monte à 10 en fabrication par condensation).",
        "**Minage** : {{Blazamut}}, {{Blazamut Ryu}}, {{Anubis}}, {{Astegon}}.",
        "**Arrosage** : {{Jormuntide}}, {{Shell Long}}, {{Suzaku Aqua}}. **Plantation** : {{Dandylord}} (aussi fabrication + pharmacie), {{Ophidia}}.",
        "**Récolte** : {{Hartelius}}, {{Jetragon}}, {{Frostallion Noct}}. **Bûcheronnage** : {{Celastius}}, {{Sibelyx}}. **Refroidissement** : {{Frostallion}}. **Électricité** : {{Orserk}}. **Transport** : {{Azurobe}}. **Pharmacie** : {{Sibelyx}}.",
      ],
    },
    {
      kind: "callout",
      tone: "tip",
      label: "Faim et santé mentale à la base",
      text: "Sortez ces Pals pour que votre base tourne plus longtemps sans crise : {{Woolipop Terra}} réduit la perte de faim de 15%, {{Shroomant}} réduit la perte de santé mentale de 10%, {{Lulu}} augmente la croissance des cultures de 50%. Leurs effets montent avec la condensation. Ajoutez une **Clinique** (un Pal assigné) pour maintenir la santé mentale, en plus des sources chaudes.",
    },
    { kind: "sub", title: "L'enclos : qui produit quoi" },
    {
      kind: "table",
      head: ["Ressource", "Meilleur Pal à l'enclos"],
      rows: [
        ["Laine", "{{Cremis}} / {{Melpaca}} (niveau 2), {{Lamball}}"],
        ["Oeufs", "{{Chikipi}}"],
        ["Lait", "{{Mozzarina}}"],
        ["Miel", "{{Beegarde}} (le seul)"],
        ["Cuir", "{{Surfent}} (le seul)"],
        ["Huile de Pal de haute qualité", "{{Dumud Guild}} (niveau 4, donne aussi de l'or) ou {{Dumud}}"],
        ["Tissu de haute qualité", "{{Sibelyx Primo}} (niveau 4) ou {{Sibelyx}}"],
        ["Organe de feu", "{{Flambelle}} / {{Rooby}} / {{Kelpsea Ignis}}"],
        ["Organe de glace", "{{Foxicle}} (niveau 3) ou {{Mau Cryst}}"],
        ["Organe électrique", "{{Sparkit}} (le seul)"],
        ["Glande de venin", "{{Depresso}} / {{Caprity Noct}}"],
        ["Fluide aquatique", "{{Kelpsea}}"],
        ["Os", "{{Sweepa}} / {{Sweetsicle}} (niveau 2), {{Tombat}}"],
        ["Or", "{{Mau}} (pur), {{Dumud Guild}}, {{Vixy}} (mix)"],
        ["Barbe à papa", "{{Woolipop}} (le seul)"],
        ["Baies rouges", "{{Caprity}} (le seul)"],
        ["Champignons + champignons de caverne", "{{Shroomer}}"],
        ["Graines aléatoires", "{{Vaelet}}"],
      ],
    },
    {
      kind: "callout",
      tone: "tip",
      label: "Astuces enclos",
      text: "{{Vixy}} est indispensable : elle déterre sphères, flèches, or et os en passif (des gigaspheres à haute condensation). {{Lulu}} augmente la croissance des cultures de +50%, {{Petallia}} augmente la récolte de +18%, et {{Cinnamoth}} donne +1 niveau de ferme à tous les autres Pals de la base juste en étant là.",
    },
  ],
};
